// Auto-generated. Do not edit!

// (in-package second_coursework.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SearchFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.roomNames = null;
      this.roomIds = null;
    }
    else {
      if (initObj.hasOwnProperty('roomNames')) {
        this.roomNames = initObj.roomNames
      }
      else {
        this.roomNames = [];
      }
      if (initObj.hasOwnProperty('roomIds')) {
        this.roomIds = initObj.roomIds
      }
      else {
        this.roomIds = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SearchFeedback
    // Serialize message field [roomNames]
    bufferOffset = _arraySerializer.string(obj.roomNames, buffer, bufferOffset, null);
    // Serialize message field [roomIds]
    bufferOffset = _arraySerializer.uint32(obj.roomIds, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SearchFeedback
    let len;
    let data = new SearchFeedback(null);
    // Deserialize message field [roomNames]
    data.roomNames = _arrayDeserializer.string(buffer, bufferOffset, null)
    // Deserialize message field [roomIds]
    data.roomIds = _arrayDeserializer.uint32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    object.roomNames.forEach((val) => {
      length += 4 + val.length;
    });
    length += 4 * object.roomIds.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'second_coursework/SearchFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ee5bd5de1a376e189bc23b781a2b45f6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string[] roomNames
    uint32[] roomIds
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SearchFeedback(null);
    if (msg.roomNames !== undefined) {
      resolved.roomNames = msg.roomNames;
    }
    else {
      resolved.roomNames = []
    }

    if (msg.roomIds !== undefined) {
      resolved.roomIds = msg.roomIds;
    }
    else {
      resolved.roomIds = []
    }

    return resolved;
    }
};

module.exports = SearchFeedback;
