// Auto-generated. Do not edit!

// (in-package second_coursework.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SearchGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.roomName = null;
    }
    else {
      if (initObj.hasOwnProperty('roomName')) {
        this.roomName = initObj.roomName
      }
      else {
        this.roomName = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SearchGoal
    // Serialize message field [roomName]
    bufferOffset = _serializer.string(obj.roomName, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SearchGoal
    let len;
    let data = new SearchGoal(null);
    // Deserialize message field [roomName]
    data.roomName = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.roomName.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'second_coursework/SearchGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '92fd3f5b5bb98ae4c37a9c24309a0a61';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string roomName
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SearchGoal(null);
    if (msg.roomName !== undefined) {
      resolved.roomName = msg.roomName;
    }
    else {
      resolved.roomName = ''
    }

    return resolved;
    }
};

module.exports = SearchGoal;
