// Generated by gencpp from file second_coursework/GetRoomCoordResponse.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_GETROOMCOORDRESPONSE_H
#define SECOND_COURSEWORK_MESSAGE_GETROOMCOORDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace second_coursework
{
template <class ContainerAllocator>
struct GetRoomCoordResponse_
{
  typedef GetRoomCoordResponse_<ContainerAllocator> Type;

  GetRoomCoordResponse_()
    : point()  {
    }
  GetRoomCoordResponse_(const ContainerAllocator& _alloc)
    : point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRoomCoordResponse_

typedef ::second_coursework::GetRoomCoordResponse_<std::allocator<void> > GetRoomCoordResponse;

typedef boost::shared_ptr< ::second_coursework::GetRoomCoordResponse > GetRoomCoordResponsePtr;
typedef boost::shared_ptr< ::second_coursework::GetRoomCoordResponse const> GetRoomCoordResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator1> & lhs, const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator1> & lhs, const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7c84ff13976aa04656e56e300124444";
  }

  static const char* value(const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7c84ff13976aa04ULL;
  static const uint64_t static_value2 = 0x656e56e300124444ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/GetRoomCoordResponse";
  }

  static const char* value(const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point point\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRoomCoordResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::GetRoomCoordResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::GetRoomCoordResponse_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_GETROOMCOORDRESPONSE_H
