// Generated by gencpp from file second_coursework/GetRoomCoord.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_GETROOMCOORD_H
#define SECOND_COURSEWORK_MESSAGE_GETROOMCOORD_H

#include <ros/service_traits.h>


#include <second_coursework/GetRoomCoordRequest.h>
#include <second_coursework/GetRoomCoordResponse.h>


namespace second_coursework
{

struct GetRoomCoord
{

typedef GetRoomCoordRequest Request;
typedef GetRoomCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRoomCoord
} // namespace second_coursework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::second_coursework::GetRoomCoord > {
  static const char* value()
  {
    return "d324a5cca6f56c33636632bf1cd930fc";
  }

  static const char* value(const ::second_coursework::GetRoomCoord&) { return value(); }
};

template<>
struct DataType< ::second_coursework::GetRoomCoord > {
  static const char* value()
  {
    return "second_coursework/GetRoomCoord";
  }

  static const char* value(const ::second_coursework::GetRoomCoord&) { return value(); }
};


// service_traits::MD5Sum< ::second_coursework::GetRoomCoordRequest> should match
// service_traits::MD5Sum< ::second_coursework::GetRoomCoord >
template<>
struct MD5Sum< ::second_coursework::GetRoomCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::second_coursework::GetRoomCoord >::value();
  }
  static const char* value(const ::second_coursework::GetRoomCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_coursework::GetRoomCoordRequest> should match
// service_traits::DataType< ::second_coursework::GetRoomCoord >
template<>
struct DataType< ::second_coursework::GetRoomCoordRequest>
{
  static const char* value()
  {
    return DataType< ::second_coursework::GetRoomCoord >::value();
  }
  static const char* value(const ::second_coursework::GetRoomCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::second_coursework::GetRoomCoordResponse> should match
// service_traits::MD5Sum< ::second_coursework::GetRoomCoord >
template<>
struct MD5Sum< ::second_coursework::GetRoomCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::second_coursework::GetRoomCoord >::value();
  }
  static const char* value(const ::second_coursework::GetRoomCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_coursework::GetRoomCoordResponse> should match
// service_traits::DataType< ::second_coursework::GetRoomCoord >
template<>
struct DataType< ::second_coursework::GetRoomCoordResponse>
{
  static const char* value()
  {
    return DataType< ::second_coursework::GetRoomCoord >::value();
  }
  static const char* value(const ::second_coursework::GetRoomCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_GETROOMCOORD_H
