(cl:defpackage second_coursework-msg
  (:use )
  (:export
   "<SEARCHACTION>"
   "SEARCHACTION"
   "<SEARCHACTIONFEEDBACK>"
   "SEARCHACTIONFEEDBACK"
   "<SEARCHACTIONGOAL>"
   "SEARCHACTIONGOAL"
   "<SEARCHACTIONRESULT>"
   "SEARCHACTIONRESULT"
   "<SEARCHFEEDBACK>"
   "SEARCHFEEDBACK"
   "<SEARCHGOAL>"
   "SEARCHGOAL"
   "<SEARCHRESULT>"
   "SEARCHRESULT"
  ))

