; Auto-generated. Do not edit!


(cl:in-package second_coursework-msg)


;//! \htmlinclude SearchGoal.msg.html

(cl:defclass <SearchGoal> (roslisp-msg-protocol:ros-message)
  ((roomName
    :reader roomName
    :initarg :roomName
    :type cl:string
    :initform ""))
)

(cl:defclass SearchGoal (<SearchGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SearchGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SearchGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name second_coursework-msg:<SearchGoal> is deprecated: use second_coursework-msg:SearchGoal instead.")))

(cl:ensure-generic-function 'roomName-val :lambda-list '(m))
(cl:defmethod roomName-val ((m <SearchGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader second_coursework-msg:roomName-val is deprecated.  Use second_coursework-msg:roomName instead.")
  (roomName m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SearchGoal>) ostream)
  "Serializes a message object of type '<SearchGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'roomName))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'roomName))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SearchGoal>) istream)
  "Deserializes a message object of type '<SearchGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'roomName) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'roomName) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SearchGoal>)))
  "Returns string type for a message object of type '<SearchGoal>"
  "second_coursework/SearchGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SearchGoal)))
  "Returns string type for a message object of type 'SearchGoal"
  "second_coursework/SearchGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SearchGoal>)))
  "Returns md5sum for a message object of type '<SearchGoal>"
  "92fd3f5b5bb98ae4c37a9c24309a0a61")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SearchGoal)))
  "Returns md5sum for a message object of type 'SearchGoal"
  "92fd3f5b5bb98ae4c37a9c24309a0a61")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SearchGoal>)))
  "Returns full string definition for message of type '<SearchGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string roomName~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SearchGoal)))
  "Returns full string definition for message of type 'SearchGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string roomName~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SearchGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'roomName))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SearchGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SearchGoal
    (cl:cons ':roomName (roomName msg))
))
